"""
Django settings for compass project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import dj_database_url
import cloudinary
from datetime import timedelta
import os
from celery.schedules import crontab # For Celery Beat

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ============================================================================
# ENVIRONMENT DETECTION - Use simple DJANGO_ENV (development or production)
# ============================================================================
DJANGO_ENV = config('DJANGO_ENV', default='development')

# ============================================================================
# ALLOWED_HOSTS - prefer explicit env var, fallback to provider detection
# ============================================================================
# First try explicit ALLOWED_HOSTS env var (comma-separated)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())
# Normalize empty values (decouple can return [''] for empty default)
ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS if h and h.strip()]
if ALLOWED_HOSTS:
    # explicit hosts provided via env
    # Always include localhost/127.0.0.1 for Docker healthchecks
    if 'localhost' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('localhost')
    if '127.0.0.1' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('127.0.0.1')
else:
    # If not provided, fall back to sensible defaults depending on environment
    if DJANGO_ENV == 'production':
        # In production, include localhost and 127.0.0.1 for Docker healthchecks
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    else:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']


# Static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# During development, include local `static` dir if it exists so `runserver` serves it
if DJANGO_ENV != 'production':
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'divisions',
    'documents',
    'grants',
    'email_templates',
    'analytics',
    'notifications',
    'task_manager',
    'core',
    'cloudinary',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'django_filters',
    'django_celery_beat',
    'corsheaders',
    'cloudinary_storage',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Must be after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ============================================================================
# CORS SETTINGS - Support both Railway and Render
# ============================================================================
if DJANGO_ENV == 'production':
    # Production CORS settings — limit origins in production and set via env if needed
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())
    CORS_ALLOWED_ORIGINS = [o for o in CORS_ALLOWED_ORIGINS if o and o.strip()]
    # If no origins provided, keep an empty list (tight by default)
    CORS_ALLOW_CREDENTIALS = True
else:
    # Development CORS settings
    CORS_ALLOW_ALL_ORIGINS = True  # Only for development
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",  # Vite dev server
        "http://127.0.0.1:5173",  # Vite dev server
        "http://localhost:3000",  # React dev server
        "http://127.0.0.1:3000",  # React dev server
    ]

# ============================================================================
# CSRF SETTINGS - Support both Railway and Render or DJANGO_ENV=production
# ============================================================================
if DJANGO_ENV == 'production':
    # Build CSRF trusted origins from ALLOWED_HOSTS when in production
    CSRF_TRUSTED_ORIGINS = []
    for host in ALLOWED_HOSTS:
        # Skip empty values
        if not host:
            continue
        # If host already includes scheme, use as-is; otherwise assume https
        if host.startswith('http://') or host.startswith('https://'):
            CSRF_TRUSTED_ORIGINS.append(host)
        else:
            scheme = 'https' if not host.startswith('localhost') else 'http'
            CSRF_TRUSTED_ORIGINS.append(f'{scheme}://{host}')

# ============================================================================
# HTTPS SETTINGS - Production security
# ============================================================================
if DJANGO_ENV == 'production':
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'compass.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'compass.wsgi.application'


# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
# Database uncomment the lines below to use sqlite
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# # PSQL Database
# DATABASES = {
#     'default': {
#         'ENGINE': config('DATABASE_ENGINE', default='django.db.backends.postgresql'),
#         'NAME': config('DATABASE_NAME'),
#         'USER': config('DATABASE_USER'),
#         'PASSWORD': config('DATABASE_PASSWORD'),
#         'HOST': config('DATABASE_HOST'),
#         'PORT': config('DATABASE_PORT', cast=int),
#     }
# }

# Production Database (Railway or Render)
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Railway or Render production with PostgreSQL service
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local development using individual variables from .env
    DATABASES = {
        'default': {
            'ENGINE': config('DATABASE_ENGINE', default='django.db.backends.sqlite3'),
            'NAME': config('DATABASE_NAME', default=BASE_DIR / 'db.sqlite3'),
            'USER': config('DATABASE_USER', default=''),
            'PASSWORD': config('DATABASE_PASSWORD', default=''),
            'HOST': config('DATABASE_HOST', default=''),
            'PORT': config('DATABASE_PORT', default=''),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# CLOUDINARY CONFIGURATION
# ============================================================================
cloudinary.config(
    cloud_name = config('CLOUDINARY_CLOUD_NAME'),
    api_key = config('CLOUDINARY_API_KEY'),
    api_secret = config('CLOUDINARY_API_SECRET')
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ============================================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}


# ============================================================================
# JWT CONFIGURATION
# ============================================================================
# rest framework jwt
# TODO: reset the access token to 5 minutes
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Custom user model 
AUTH_USER_MODEL = 'accounts.User'

# for http redirect
ALLOWED_REDIRECT_SCHEMES = ['http', 'https', 'ftp', 'ftps', 'mailto']

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================
# Celery Configuration Options
# Make sure Redis is running: sudo systemctl start redis-server or redis-server

# Get Redis URL from environment (works for both local and production)
REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi' 

# Celery Beat Settings
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_BEAT_SCHEDULE = {
    'expire_pending_grants_daily': {
        'task': 'grants.tasks.run_expire_pending_grants_command', 
        'schedule': crontab(minute='35', hour='3'),  
    },
    'check_grant_deadlines_daily': {
        'task': 'notifications.tasks.check_grant_deadlines_and_notify_task',
        'schedule': crontab(minute='17', hour='2'),  
    },
     'cleanup-expired-bin-items-daily': {
        'task': 'core.tasks.cleanup_expired_recycle_bin_items',
        'schedule': crontab(hour=0, minute=0), # Runs daily at midnight
    },
}

# ============================================================================
# SWAGGER SETTINGS
# ============================================================================
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': "IMPORTANT: Enter the token with the 'Bearer ' prefix (e.g., 'Bearer eyJhbGciOiJIUzI1Ni...').",
        }
    },
    # If you want to enforce JWT for all protected endpoints in Swagger UI:
    'SECURITY_REQUIREMENTS': [{
        'Bearer': []
    }],
    'USE_SESSION_AUTH': False,  # Disable session authentication in Swagger UI if you only use JWT
}

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }