# Generated by Django 5.2.1 on 2025-05-18 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nisria', 'Nisria'), ('maisha', 'Maisha')], max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(limit_choices_to={'role': 'management_lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('student_location', models.CharField(max_length=255)),
                ('student_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('school_associated', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.division')),
                ('maintainer', models.ForeignKey(limit_choices_to={'role__in': ['grant_officer', 'management_lead', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicroFundProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('person_name', models.CharField(max_length=255)),
                ('chama_group', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.division')),
                ('maintainer', models.ForeignKey(limit_choices_to={'role__in': ['grant_officer', 'management_lead', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RescueProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('child_name', models.CharField(max_length=255)),
                ('is_reunited', models.BooleanField(default=False)),
                ('under_care', models.BooleanField(default=True)),
                ('date_joined', models.DateField()),
                ('date_reunited', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('place_found', models.CharField(max_length=255)),
                ('rescuer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.division')),
                ('maintainer', models.ForeignKey(limit_choices_to={'role__in': ['grant_officer', 'management_lead', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VocationalTrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('trainer_name', models.CharField(max_length=255)),
                ('trainer_association', models.CharField(max_length=255)),
                ('trainer_phone', models.CharField(max_length=20)),
                ('trainer_email', models.EmailField(max_length=254)),
                ('trainee_name', models.CharField(max_length=255)),
                ('trainee_phone', models.CharField(max_length=20)),
                ('trainee_email', models.EmailField(max_length=254)),
                ('trainee_association', models.CharField(max_length=255)),
                ('date_enrolled', models.DateField()),
                ('under_training', models.BooleanField(default=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.division')),
                ('maintainer', models.ForeignKey(limit_choices_to={'role__in': ['grant_officer', 'management_lead', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
