# Generated by Django 5.2.1 on 2025-09-29 08:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_division_deleted_at_division_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationprogramdetail',
            old_name='school_associated',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='educationprogramdetail',
            old_name='student_contact',
            new_name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='educationprogramdetail',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='educationprogramdetail',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='educationprogramdetail',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='educationprogramdetail',
            name='student_location',
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='medical_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='other_support_details',
            field=models.TextField(blank=True, help_text='Support from sources other than this program.', null=True),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='pictures',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='education_pictures'),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationprogramdetail',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
