# Generated by Django 5.2.1 on 2025-05-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_alter_division_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(choices=[('nisria', 'Nisria'), ('maisha', 'Maisha')], max_length=100, unique=True),
        ),
    ]
