# Generated by Django 5.2.1 on 2025-09-29 09:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0003_rename_school_associated_educationprogramdetail_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microfundprogramdetail',
            name='start_date',
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='additional_support',
            field=models.TextField(blank=True, help_text='Details of any additional support received apart from this program.', null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='money_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='pictures',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='microfund_pictures'),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='progress_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='project_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='role_in_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='site_visit_notes',
            field=models.TextField(blank=True, help_text='Record of dates and notes from site visits.', null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microfundprogramdetail',
            name='testimonials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
