# Generated by Django 5.2.1 on 2025-05-21 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0003_alter_division_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microfundprogram',
            name='division',
        ),
        migrations.RemoveField(
            model_name='microfundprogram',
            name='maintainer',
        ),
        migrations.RemoveField(
            model_name='rescueprogram',
            name='division',
        ),
        migrations.RemoveField(
            model_name='rescueprogram',
            name='maintainer',
        ),
        migrations.RemoveField(
            model_name='vocationaltrainingprogram',
            name='division',
        ),
        migrations.RemoveField(
            model_name='vocationaltrainingprogram',
            name='maintainer',
        ),
        migrations.RemoveField(
            model_name='division',
            name='lead',
        ),
        migrations.AddField(
            model_name='division',
            name='leads',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['management_lead', 'super_admin']}, related_name='led_divisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('education', 'Education'), ('microfund', 'Microfund'), ('rescue', 'Rescue'), ('vocational', 'Vocational')], max_length=100, unique=True)),
                ('description', models.TextField()),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.division')),
                ('maintainers', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['grant_officer', 'management_lead', 'admin', 'super_admin']}, related_name='maintained_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MicroFundProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('chama_group', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.program')),
            ],
        ),
        migrations.CreateModel(
            name='EducationProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('student_location', models.CharField(max_length=255)),
                ('student_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('school_associated', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.program')),
            ],
        ),
        migrations.CreateModel(
            name='RescueProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('is_reunited', models.BooleanField(default=False)),
                ('under_care', models.BooleanField(default=True)),
                ('date_joined', models.DateField()),
                ('date_reunited', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('place_found', models.CharField(max_length=255)),
                ('rescuer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.program')),
            ],
        ),
        migrations.CreateModel(
            name='VocationalTrainingProgramTrainerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=255)),
                ('trainer_association', models.CharField(max_length=255)),
                ('trainer_phone', models.CharField(max_length=20)),
                ('trainer_email', models.EmailField(max_length=254)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.program')),
            ],
        ),
        migrations.CreateModel(
            name='VocationalTrainingProgramTraineeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=255)),
                ('trainee_phone', models.CharField(max_length=20)),
                ('trainee_email', models.EmailField(max_length=254)),
                ('trainee_association', models.CharField(max_length=255)),
                ('date_enrolled', models.DateField()),
                ('under_training', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.vocationaltrainingprogramtrainerdetail')),
            ],
        ),
        migrations.DeleteModel(
            name='EducationProgram',
        ),
        migrations.DeleteModel(
            name='MicroFundProgram',
        ),
        migrations.DeleteModel(
            name='RescueProgram',
        ),
        migrations.DeleteModel(
            name='VocationalTrainingProgram',
        ),
    ]
