# Generated by Django 5.2.1 on 2025-09-29 10:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0004_remove_microfundprogramdetail_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='date_enrolled',
        ),
        migrations.RemoveField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='trainee_association',
        ),
        migrations.RemoveField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='under_training',
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='additional_support',
            field=models.TextField(blank=True, help_text='Support from sources other than this program.', null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='pictures',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vocational_trainee_pictures'),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='post_training_status',
            field=models.CharField(blank=True, choices=[('self_employed', 'Self-Employed'), ('employed', 'Employed'), ('further_education', 'Further Education'), ('unemployed', 'Unemployed'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='quarterly_follow_up',
            field=models.TextField(blank=True, help_text='Notes from quarterly follow-ups.', null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='training_received',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
