# Generated by Django 5.2.1 on 2025-05-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0005_educationprogramdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogramdetail',
            name='student_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='microfundprogramdetail',
            name='person_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rescueprogramdetail',
            name='child_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vocationaltrainingprogramtraineedetail',
            name='trainee_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vocationaltrainingprogramtrainerdetail',
            name='trainer_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
