# Generated by Django 5.2.1 on 2025-09-29 10:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0005_remove_vocationaltrainingprogramtraineedetail_date_enrolled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescueprogramdetail',
            old_name='notes',
            new_name='case_referral_description',
        ),
        migrations.RenameField(
            model_name='rescueprogramdetail',
            old_name='date_reunited',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='rescueprogramdetail',
            old_name='rescuer_contact',
            new_name='guardian_phone_number',
        ),
        migrations.RemoveField(
            model_name='rescueprogramdetail',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='rescueprogramdetail',
            name='is_reunited',
        ),
        migrations.RemoveField(
            model_name='rescueprogramdetail',
            name='place_found',
        ),
        migrations.RemoveField(
            model_name='rescueprogramdetail',
            name='under_care',
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='background',
            field=models.TextField(default='', help_text='A short background of the child’s situation before rescue'),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='case_referred_from',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='case_type',
            field=models.CharField(choices=[('lost_and_found', 'Lost and Found'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='case_type_other',
            field=models.CharField(blank=True, help_text="Specify if case type is 'Other'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='children_office_case_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='date_of_exit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='date_of_rescue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='educational_background',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='family_reunification_efforts',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='guardian_residence',
            field=models.CharField(blank=True, help_text='Original residence or location of parents/guardian', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='health_status',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='location_of_rescue',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='medical_support_details',
            field=models.TextField(blank=True, default='', help_text='Details of medical support received since rescue', null=True),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='ob_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='pictures',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='rescue_child_pictures'),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='post_rescue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescueprogramdetail',
            name='urgent_needs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rescueprogramdetail',
            name='age',
            field=models.IntegerField(help_text='Age or predicted age'),
        ),
    ]
