# Generated by Django 4.2.25 on 2025-11-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0006_rename_notes_rescueprogramdetail_case_referral_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='annual_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual budget for this division', max_digits=15),
        ),
    ]
