# Generated by Django 4.2.25 on 2025-11-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0007_division_annual_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocationaltrainingprogramtraineedetail',
            options={'ordering': ['-created_at']},
        ),
    ]
