# Generated by Django 4.2.25 on 2025-11-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0009_alter_microfundprogramdetail_role_in_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microfundprogramdetail',
            name='role_in_group',
            field=models.CharField(choices=[('chairperson', 'Chairperson'), ('member', 'Member')], default='member', help_text="Member's role in the chama group", max_length=20),
        ),
    ]
