# Generated by Django 5.2.1 on 2025-05-26 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='assigner',
            field=models.ForeignKey(blank=True, help_text='User who triggered the notification, if applicable (e.g., task assigner).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
