# Generated by Django 5.2.1 on 2025-05-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_assigner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('grant_deadline_reminder', 'Grant Deadline Reminder'), ('bank_statement_access_granted', 'Bank Statement Access Granted'), ('general', 'General Notification')], default='general', max_length=50),
        ),
    ]
