# Generated by Django 5.2.1 on 2025-05-20 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_alter_document_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('application_link', models.URLField(blank=True, null=True)),
                ('amount_currency', models.CharField(max_length=10)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('contact_tel', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('normal', 'Normal Company'), ('grant_awarder', 'Grant Awarding Company')], max_length=20)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('required_documents', models.ManyToManyField(related_name='grants_requiring', to='documents.document')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submitted_documents', models.ManyToManyField(blank=True, related_name='grants_submitted', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='GrantExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estimated_depletion_date', models.DateField(blank=True, null=True)),
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure', to='grants.grant')),
            ],
        ),
    ]
