# Generated by Django 5.2.1 on 2025-05-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='application_link',
            field=models.URLField(default=''),
        ),
    ]
