# Generated by Django 4.2.25 on 2025-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_grant_deleted_at_grant_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='contact_tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
