# Generated by Django 5.2.1 on 2025-05-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_alter_grant_application_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantexpenditure',
            name='grant',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.DeleteModel(
            name='GrantExpenditure',
        ),
    ]
