# Generated by Django 4.2.25 on 2025-11-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0007_division_annual_budget'),
        ('grants', '0003_alter_grant_contact_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='associated_program',
            field=models.ForeignKey(blank=True, help_text='The specific program this grant is associated with, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_grants', to='divisions.program'),
        ),
    ]
