# Generated by Django 5.2.1 on 2025-05-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0006_alter_educationprogramdetail_student_name_and_more'),
        ('grants', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='program',
            field=models.ForeignKey(blank=True, help_text='The specific program this grant is associated with, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='divisions.program'),
        ),
    ]
