# Generated by Django 5.2.1 on 2025-05-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_grant_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='organization_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
