# Generated by Django 5.2.1 on 2025-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_alter_grant_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='organization_name',
            field=models.CharField(max_length=255),
        ),
    ]
