# Generated by Django 5.2.1 on 2025-05-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_alter_grant_organization_name'),
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grant',
            field=models.ForeignKey(blank=True, help_text='Link to a grant if this task is related to one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='grants.grant'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_grant_follow_up_task',
            field=models.BooleanField(default=False, help_text='True if this task was auto-created for a pending grant.'),
        ),
    ]
