# Generated by Django 5.2.1 on 2025-05-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('cbo_cert', 'CBO Certificate'), ('ngo_cert', 'NGO Certificate'), ('impact_report', 'Impact Report'), ('pitch_deck', 'Pitch Deck'), ('monthly_budget_nisira', 'Monthly Budget (Nisira)'), ('monthly_budget_maisha', 'Monthly Budget (Maisha)'), ('yearly_budget_nisira', 'Yearly Budget (Nisira)'), ('yearly_budget_maisha', 'Yearly Budget (Maisha)'), ('overall_budget', 'Overall Budget')], max_length=50)),
                ('document_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('docx', 'DOCX'), ('canva', 'Canva'), ('pptx', 'PPTX'), ('jpg', 'JPG'), ('png', 'PNG')], max_length=20)),
                ('document_link', models.URLField()),
                ('division', models.CharField(choices=[('overall', 'Overall'), ('nisira', 'Nisria'), ('maisha', 'Maisha')], max_length=20)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
