# Generated by Django 5.2.1 on 2025-05-19 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('bank_statement', 'Bank Statement'), ('cbo_cert', 'CBO Certificate'), ('ngo_cert', 'NGO Certificate'), ('impact_report', 'Impact Report'), ('pitch_deck', 'Pitch Deck'), ('monthly_budget_nisria', 'Monthly Budget (Nisria)'), ('monthly_budget_maisha', 'Monthly Budget (Maisha)'), ('yearly_budget_nisria', 'Yearly Budget (Nisria)'), ('yearly_budget_maisha', 'Yearly Budget (Maisha)'), ('overall_budget', 'Overall Budget')], max_length=50),
        ),
        migrations.CreateModel(
            name='BankStatementAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_granted', models.BooleanField(default=False)),
                ('document', models.ForeignKey(limit_choices_to={'document_type': 'bank_statement'}, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
