# Generated by Django 5.2.1 on 2025-06-03 12:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id_int', models.PositiveIntegerField(blank=True, help_text='The primary key of the deleted item if integer.', null=True)),
                ('object_id_uuid', models.UUIDField(blank=True, help_text='The primary key of the deleted item if UUID.', null=True)),
                ('original_data', models.JSONField(help_text="A JSON representation of the deleted item's data.")),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(help_text='The model of the deleted item.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_items_in_bin', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_items_from_bin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recycle Bin Item',
                'verbose_name_plural': 'Recycle Bin Items',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
