# Generated by Django 5.2.1 on 2025-05-20 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('grant_application', 'Grant Application'), ('partnership_appeal', 'Partnership Appeal'), ('service_provision_contract', 'Service Provision Contract'), ('program_application', 'Program Application'), ('impact_Update_to_donors', 'Impact Update to Donors'), ('employee_contract', 'Employee Contract'), ('concept_note', 'Concept Note')], max_length=50)),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField(help_text='Use {{placeholders}} for dynamic fields.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_email_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
