# Generated by Django 5.2.1 on 2025-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
